[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"

[rpc_endpoints]
chiliz_spicy = "https://spicy-rpc.chiliz.com/"

[etherscan]
chiliz_spicy = { key = "${ETHERSCAN_API_KEY}", url = "https://spicy.chz.tools/api" }

[fmt]
line_length = 120
tab_width = 4

[profile.default.optimizer]
enabled = true
runs = 200