[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@thirdweb-dev/=lib/thirdweb-contracts/"
]

# Chiliz Spicy Testnet configuration
[rpc_endpoints]
chiliz_spicy = "https://spicy-rpc.chiliz.com/"

[etherscan]
chiliz_spicy = { key = "${ETHERSCAN_API_KEY}", url = "https://testnet.chiliscan.com/api" }

# Compiler settings
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = false

# Gas settings optimized for Chiliz
gas_limit = 30000000
gas_price = 1000000000  # 1 gwei

# Enable ffi for deploy scripts
ffi = true
fs_permissions = [{ access = "read-write", path = "./deployments" }]

# Cache settings
cache = true
cache_path = "cache"
force = false

# Test settings
verbosity = 2
